osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- rvm use ruby-2.4.1
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends
  -y icnsutils graphicsmagick xz-utils; fi
install:
- nvm install 8
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- npm install
script:
- npm run build
branches:
  only:
  - master
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: E+qmaYp+EfwivvB2kNOZcivB8FpRc8VbpVNXDg3LajzWhb2W49fUXgqlhnYTv/Ed/TtYgch9Vx0XHmoCzh2xmRyE7m1/UKONEITA1ujKJXtpVXk553KOTkE7v307BB0hT1/FB5eS8Cd77amVgOdVB+pMyhTwrfymji8/VnP00MIwr/Ck1cVNo6W9/hCxNS0HkmqHWE7rv4CWZJeE8KuLTjbEm8qtLaQ3tFbBq4i+oxc/9r95dZ5SkjBg60V3I/isC8Tb6eQxaBuaMZbE8LE2Yl838qNl78gCuhzJoUXalw8TxFt0hDUM1D5ial5maLaYN0NTQC87BKAXNnqEIoym3J6lcXFMNvTz9y7zVaK8i03S9Cq+/Y1CH8Nmx2i10DNcOam60V36/gMBjGNtYJCbTsX38sTmmla0DAtdlHoXeTXom78W9qvQY/otgrNUKJlq3CwWZ3iL2lxdd0ROaqB6hMoQKQWT/zx+myGzi9oYlJ5aVNfKP1tbOmZtwG6s3y99oD0WZfpjVHYb7StTu8TBl0IqU1UujsTVVsiFIUYOo4RxA4zwMQJ4LpUuir05uCyyLLxp3cWk2c6wrvuv1JTgimN9vy5YV/Z97uT4Kb/ApNiDSUsmTcw+1rSZg/wrHSnvJsTcFbTO73iEZMsLTlwWlVMIXOPHoYl5MlULSY2j6T8=
  file: build/*
  skip_cleanup: true
  on:
    # branch: master 
    tags: false
# repo: cyy0418/ceditor
