osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends
  -y icnsutils graphicsmagick xz-utils; fi
install:
- nvm install 7
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn
script:
- yarn run build
branches:
  only:
  - master
env:
  global:
  - secure: oow8YzcpUItdZ7uatCxbiMYG81BZ8tJNg/GaEpv55XEJn2iE1G1SnwBe1EPnIFImiax84SzleRlVvCSwJ1VYRD+P8NGM4j1xQdxIpKzKgmVLiOnnmXL++AubaWKoAoijPavVYvRDCOFGoKXuklUeT+Hlj7s0iOLrDj5vJq0/N2B6SYyPvELblDNA3gosUYRy48suA+wi08fRQSx5eUyYgt9cGMfG3BoxBivV2zOGHrxoCDmyJZl04gXQWsxBKf6xJ6HuwRuOsb1+I5rMrm4EVeS5zesQSIrqE89qesbOzK0pfG4of3wJ5l1YOFmKrsjzc3AhBhxhhDW3YlRbLLbH9v6hxZY7wkY1OBPZQmAzbjtocuJseVDv5nBExkoaexp4+MdWd6KIp9O7AXv1CSUySydzEWyX+kG7olRlNL3v/Rs1sU5EeVSV6EdaaYAAzSQxKMN0ze99nrJnCvKzCCbSDP9XAvUMVXauGi97x1V4ufp+tqi5tQzHnCWPirrV6yGuImI45wEOpINyu3V3XjJjYdT5vijH7XVF/w5JgzOGmiKQQNgcSidDaDXKiDSusr2t8YPSgyHlhrOI9obAT+slkk+sbQ8us6gz4kiDId46LuoyuPnf5nb9IhDV5gG4VaT5VQdhmcNfFlDdCT+TlbnmupRK7X1hRoGOY/sDytjdpj8=
  - secure: LGY5MfZcOqElbQru5f5enQHwap5pRATg1BKYqpzvU1mUeXFzEI6LcNkDqTYZ0vvVEddbgUgVfVYj6lE7DqoHKToC1d3KgFK5W/m/IqBsWeixxR24UUDF3ZRL4rTNHNMJG8L05rL4aMfxXzqfb1GYVAQYCr3SClW/0aTee9GLI/lzd+2tBRaCsZDP8NL0g8DJf+vHte9j4vjiiE2W4KvAhJwRKQanXyxZNVvvYG8dLV4M0HDB5p+ebFZnP8FhQ6/KsQzzDOtPw85sKHkSJ7PlAgGxub5bCBPa9GvMAChN67tv+agwkSXBgSHOPSOrd3dnVX8DOzo6XJ8b36Z6aOpAbctjNUGg6Tej6fDRckcWGV8kCotDw8z9TTGdfmg73r1c5KlIIZVJeZ66p6bn1WoHKfaSBxoONcEbXsxzdpOK0WHIkNMUv4BKPS+XB4IL5g5bF3AlmjFUx/dB6/Kq6ajA2b/XxiFOSD8KTS6On9igEbSGwgh8h77sTT0Coxc46FcVNW8pbYxIIai5vXKTGVIo1LUS2+vTzWZlIQuqrzOCT8ijVIxFHUNAMOFCICq+I/gbT1vDgQ+6wBgf+T7iZXThQaYYzb0tsagM4dqDZdYudveyLCnNaZRp1zxc2LmMlYjJMyQNDXEDa6GWpjJkeN3y4NwbGr7Ei1t1duRJ/Yv1uhI=
  - secure: krOTxA80gvRWLUdK+o/6t6T1x8JArEBWfZSrdQ4XwIMYdKGYvQvQXfPAejYPBmaHRo8C3FoBFGZ6wH6ZUW4OZRtAUMa5KD+aXMTNTVXTum4joyBgHgFaSktM45hVzMj3kw2UITbpaZ2D+AkK66WZqLTLG2uU230jt9oq+TUBRNYxCJbJ4DlkyWqcFxkier8LyhSsgWgneZIzqZjGi1x86Ypnzgz8Xx4ryEA+eVzGg1Xv3YNjNInXR5ETpkQO5zybxg1zeaVQv3tlIX4jB/kmxPmOMZUfGy9Dq9B/zV9svtdJoImKuIWqqLgGGZMTKJ6SyYRpGKTZpHqiHDBEksaUBw/4hDBy0ZHPo46C+LvgUYWEQ9rXZ6+6YVOEc2ibkyld0hBDS36b1TIM7/AdBEgtW7nQaavyqSiPvbm30ErIQEa+9diviFAjRAyfc7cBILXfzqomL9a6W4jy+lSQJt8pK0VY9+uqDpm9A7RHBc/zBvTPV75ZC3LdbonAbHFGHtETRgqfUoy5kDtX2/k0l7Dk6xwU83PflbfKTS1EJofw+NxB6EV9H/8P5PW5OcmH4JEijyJ51tFimNrvrCN6yVPx93TeBs0RrIv18VSJNuRUUYTIRiGdnc5dGYW1U5CK9f+9slh7pQvzcz4VtzBZiBqbrUqEEktF58vakMHk5/v3mq0=
  - secure: jckh8QidAzcp3DgaQXwnh2Ayz6hQf/o0D0rySoU2pj93Bx/8ks7NM+FfJXvmnFCDfUJPFSqAVgjKot7DsZ8Q9kl+EJRPuZCNRZNfbjf57tHsobgo2xwGaf9+a4rxEUOBJzGIdkWdQ5+pgeDo4L3sG57SCSD3/oL/3R07b/7wogBp2xuu0w2nmEORMzcf8gdVymvooiv+qCY/X8wxpX34Z68bAt6d/oh3TuYHmKL6KDONDvpYt1MEAdcK2wQnOhugvaet/N36oiLcqTAbTUzm/v9SFSybTrcI1sHPWo2bEijh449uNGbZKP0aRtr4vBuyDNE2L+Ge1wkaY5GMsNa9STQ1pLR+TyW1By7Y+16OHYgLuKddGWcXdW9706gGZgUyBFbC6dV9HejTBdn7sBpZShSv5tMK/RkE3p6MYGKKRPpohYzjzb6iEOlC7DWCwsusKLinQYwH5aywdhitZ/+0+0XsUbeHSzNwHj1ce5+N++IXya9ID3jAuV0udLGsRLS5fXxsbdmGWYwBTxK8k/cJfT1P9hMkZYXXItCV09eE2xobRaCVIKHsbSZngNCzYkP1f8IgsYAwLzi4xrUe9H9YZXtpkV7VsPlE3pdtEoUvju9A18guSyyINUAYcYtTBMKSuqiaOatM/stIvqaPKkyf+i5NJxdEOxYNx0W+/0qH2U0=
  - secure: SErf/hhNlLoWFbxAhq4KwA4ryIUvv8bHsZ3fhsgaIxXBM02xIza7kk0FvLqrEaXXkswNZltOIloakOZVDsZhC/hXPISxpKz1X3G63zVMcpUDIXRlj12cUve3ATXBPEkriWzeCdn3DvIXpCMDCXajhkPYVItW62iyD3UDvFEv9Q/GZHFA9+sF+vtNbHEfBFlYuP5+I0kdFYHk7qj5lZ5cjOqqjdecn7XKnZA4evIVyc+YuKZQdOhjSthxlB1/DDcuXS/UEThYAyyesgsT4wCICos0LxbsHwMRtYQEixBPYJarwqXTwzHJ6fsEEK/cngyO9e16C6b7KZtOMsB3+CyhPEDSZkTOr/DCayQNZlwv1Qbv6b+9aZWAgl26ayBp9xD4jYMAbFkqS2x0fRaQ3l6VrYm9dBUO4vY/t9PmqrkuKJXEtjOM8OZroxB79xCw/l1295lNXD/DJSzWaQUIc3xHQRETHIcqH+wIq7aicisnlxIndUbz+mCGHqegP6pLfANpO+UGlFthu6PBBDdbzAdjpdFPJseBhZJZyTCJcMLnC1mxQowprIbX4GT5WLWVVB+Yz6Fyc1MvE0+dM+BA0BmTVKe/QGImHUKvcMrhf9MZRJwpN2/kiQEUE0Wrho0932mVr/UpYx3oGkRKMQFjdiNB5ZbHczMCUwREhtnC/DByP5Q=
  - secure: t6Ny9O0ZHcXMW0VlFWccSj4sDruJs/4yM3X/aDGGwxhiIxZ2QkHaUsJMrOmetMNeKmEaYiFXk2jKXhA9ihK/YmhvBGZymRsXzYHxiFallQLTzq+4/G1y4BkrCc2G/ZTfoKLt2Zhlkc5KKi42jF5+0b3sdIiucYOq3wpqsKC/n7qGh1z2/rToFlmbzg77jVGxviC1R80K306Sjdpp0s92bwlCANFL4ebpSG1D0Nb979rL1mDk0A/kY11irdtVPuqXWoS7T4oOoxWEk7rgyx9TUGtYemh3thbBkddMFWKT5YRtpu9Ht2Xiehm5CeaapArDDlXrKADnkXqjYv3vTJX/CSwlwd+T1W4y04L5CVKlPj+ipMo/t222ydmfVipqfA0puqBwVrJcLWPPaBHfL4e19VZtltbP1UC06YqFgwblF/BjK3AcNybvrArzcgAhM2zpMM1RinmjJOciRnzOZ3NZvtIXL40YCm2ICsBaZY+I/KaeKjzz8Oem0/qpeGPuDgQc/UjEPwpCT/IaMXV2BPNwOgdG6aJCb4NFRzg2PlmlEllAo9sALhAK67rXIplXne/9vqkszsC4tjCH9wjl+FjwjMIz6F30laqB+r4/Kt7ZefETsrbHU1XOXd/gIjP7wf/3JoxU7RMlsFvRbWlfcRo54ZaGWoiFaIeiW+OO2vAt0kI=
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: dt49unvgsKONFwr/tN+yPN8CdYn1HAZhf+Gy2nZmmMnIKkqoIJIbUNglslcJPeH5mO3pPr9QAtKsTVMuuymsSf5w3/OtX7vLCMx1pUvRx4rfAYKEbusUKi4XnA2oYFAmH5BBxsjS0iskdHvKyPwFJH+8CAUxWaRGVHHf0HahJG4JHBtm9uHn7qo38ousZzm6hWx7ME1KAOzE73t3hRrtXiJI4EkvSuWxL3rJDxczr1FEiUReqZVTKR6cBIlgUNAzw48Y19b7vK9V8L0u8E1BrT27ZWwFat7ouj4Yw9W7ufsJnf50+8ohkwYpYPjv3MWcASDQHjC6WdtJ7wzsHdl+frRUB9bkVF6QNQqB0ej992KD3G5ZxV71yrzUcNDhfK6GslvTREEz7NRU6tB9B2eQmy1fjGhNp2ymJg9ahDjADe6DvP32vWg31X0Sg8YuMZbCUTrbiuEjDXW0YEf7Zob5NjfuIiJi4WO5FbMV4jMaqYSIAeBM6UaUC0b1ZRi3nhkUurlvvjt8RvoERC1GeCmdpu5kKeTsu2upk5JfY3zZkynEnpqV4QrqbNvATPk4WXJCDeRU8l0kGNbJEcFZobcDAURCGOkfYnRs0Po7/TWaIF+E1vcLtb9wzafRNcLXZB9C2gX6u5N2bt2o0zQ68QsPoD15XIF7botPLjYXmFZv1ZE=
  file: build/*
  # on:
  #   tags: true
