# Commented sections below can be used to run tests on the CI server
# https://simulatedgreg.gitbooks.io/electron-vue/content/en/testing.html#on-the-subject-of-ci-testing
version: 1.0.{build}
skip_non_tags: true
shallow_clone: true
branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - npm install
  - node --version
build:
  verbosity: minimal
build_script:
  #- yarn test
  - npm run build

test: off
deploy:
- provider: GitHub
  tag: 1.0.0
  release: 1.0.0
  description: 'Release'
  auth_token:
    secure: AAtnf9eJWdGGr6Ce4idQKaRA8BnrNhS1uOzcXlksTUYiXWKQhceZdH9hcKBqwuwe # your encrypted token from GitHub
  repository: cyy0418/ceditor
  artifact: /.*\.nupkg/
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
